<paste log output from Kubernetes-mediated prediction, here>
#Note those Errors have been made on purpose as the Deployment and Services were already on running state.
error: failed to create deployment: deployments.apps "ml-app" already exists
NAME     READY   UP-TO-DATE   AVAILABLE   AGE
ml-app   1/1     1            1           43m
NAME                      READY   STATUS    RESTARTS   AGE
ml-app-7675869dcb-29wpw   1/1     Running   0          43m
NAME         TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1      <none>        443/TCP   50m
ml-app       ClusterIP   10.105.19.43   <none>        80/TCP    8m31s
Error from server (AlreadyExists): services "ml-app" already exists
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000


<output from the command --> kubectl logs ml-app-7675869dcb-29wpw in another terminal>
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 141-053-718
127.0.0.1 - - [27/Mar/2021 16:41:18] "GET / HTTP/1.1" 200 -
[2021-03-27 16:54:14,672] INFO in app: JSON payload:
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2021-03-27 16:54:14,808] INFO in app: Inference payload DataFrame:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2021-03-27 16:54:14,871] INFO in app: Scaling Payload:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2021-03-27 16:54:14,889] INFO in app: output prediction: [20.35373177134412]


